// <auto-generated />
namespace Flight_Doc_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class document1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(document1));
        
        string IMigrationMetadata.Id
        {
            get { return "202211150431549_document1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
